### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by nkgm** [arikw/chrome-extensions-reloader#12]
I'm a bit puzzled as to how this is supposed to work. When I click the button or `http://reload.extensions`, it seems to do something (buttons repopulate). However when I check my (unpacked) extension, it hasn't reloaded. 

A couple of things I've tried:
* Change the `name` in my `manifest.json` and see if it updates in action popup and tooltip
* Remove a `content_script` and refresh the page after running `http://reload.extensions`

None of the above worked. Clicking `Reload` for my extension on `chrome://extensions` worked every single time. Am I missing something obvious?

**Comment by levithomason** [comment]
Same here. I believe I used this extension quite some time ago without issue, however, it is no longer working.

**Comment by nkgm** [comment]
Probably related to https://bugs.chromium.org/p/chromium/issues/detail?id=178319. You can still trigger a reload within your extension without the need of a plugin, using code like this:

```js
chrome.webRequest.onBeforeRequest.addListener(
  function(details) {
    if (details.url.indexOf("http://myextension.reload") >= 0) {
      chrome.runtime.reload();
      return {
        redirectUrl: 'javascript:void(0)'
      };
    }
    return {cancel: false};
  },
  {
    urls: ["http://myextension.reload/"],
    types: ["main_frame"]
  },
  ["blocking"]
);
```
You will also need the `webRequestBlocking` permission. More info [here](https://developer.chrome.com/extensions/webRequest).

Leaving this issue open for future visitors, but ultimately there should be a `README` notice.

**Comment by arikw** [comment]
Changes to your extension's manifest.json file will not be reflected using "Extensions Reloader" and a manual refresh must be done to apply them.
Updated the documentation.
