### ISSUE TITLE
Doesn't refresh changed manifest.json files

### ISSUE THREAD

**Issue by beingmrkenny** [arikw/chrome-extensions-reloader#13]
Love this extension, saves so much time.

Have noticed (for a few years now actually) that the extension only reloads the content scripts which are already loaded. This is great if I change a JS/CSS file, but not when I add a new file to the manifest.json. In that case I have to go to the extensions page itself and reload manually.

Is this a limitation of Chrome's API or could this be added in a future version?

**Comment by arikw** [comment]
When I built the extensions, it certainly was a Chrome limitation.
Not sure if the situation has changed since then...

**Comment by studgeek** [comment]
It's probably worth documenting in the README if it is still the case.

**Comment by arikw** [comment]
Docs updated with the help of @studgeek. Thank you!
