### ISSUE TITLE
Endless reload loop

### ISSUE THREAD

**Issue by Revadike** [arikw/chrome-extensions-reloader#16]
When you open http://reload.extensions in a new chrome tab and have "Reload current tab after extensions have been reloaded." enabled, it will get stuck in an endless reload loop. Please fix this.

**Comment by FilipRoseen-refp** [comment]
I don't know if this repo is dead given that the version on the chrome extension store is `1.14`, whereas the version in this repo is `1.12`; but fingers crossed for this getting merged, @Revadike. I have been annoyed by this issue myself and just now decided to do something about it.

Doing something like `xdg-open http://reload.extensions` from a *shell-script* is heaven, and if you want to automatically refresh a tab this fix is needed.

**Comment by arikw** [comment]
@Revadike @FilipRoseen-refp 
Thank you for your contribution.
I'm really short on time and will review the PR as soon as I'll get the chance.

**Comment by arikw** [comment]
@Revadike 

I've reproduced this issue by running `start "http://reload.extensions"` from windows command prompt

**Comment by arikw** [comment]
@Revadike @FilipRoseen-refp Would appreciate your review on PR #18
