### ISSUE TITLE
http://reload.extensions not working

### ISSUE THREAD

**Issue by morninj** [arikw/chrome-extensions-reloader#26]
`http://reload.extensions/` isn't working for me. I'm using Chrome v118.0.5993.88 (Official Build) (x86_64). I've tried to access that URL from the browser and a few command line tools.

**Comment by arikw** [comment]
Thank you for reporting this issue.

When opening `http://reload.extensions/`, you should see an "OK" badge on the extension icon as follows:
![image](https://github.com/arikw/chrome-extensions-reloader/assets/7900646/82a2741e-a574-4568-8280-5a7e3e2fd144)

What happens when you open that url?

**Comment by morninj** [comment]
It appears to be working now in the browser. The "OK" badge appears and the extension reloads. However, I'm not able to access `http://reload.extensions/` via `curl`.

**Comment by morninj** [comment]
Ah. Thank you!

In case anyone gets here via Google, I got this to work on macOS with `open -a "Google Chrome" http://reload.extensions/`.
