### ISSUE TITLE
Bug: content script cannot be loaded when using relative path

### ISSUE THREAD

**Issue by onGstring** [arikw/chrome-extensions-reloader#5]
The original problem is displayed [here](http://stackoverflow.com/questions/34554692/chrome-extension-content-script-cannot-be-loaded-when-using-relative-path)

I found the problem lies in the reload extension.

**Comment by arikw** [comment]
Some manifest changes aren't reflected even after a reload - Is this what you are referring to?

**Comment by onGstring** [comment]
Yes, it seemed so.

**Comment by arikw** [comment]
Currently some changes to the manifest.json can't be reloaded due to the nature of Chrome's API
