### ISSUE TITLE
Add keyboard shortcut

### ISSUE THREAD

**Issue by tslater** [arikw/chrome-extensions-reloader#7]
It would be nice to have a keyboard shortcut to reload the extension.

**Comment by tylercollier** [comment]
@arikw Is Alt+r a shortcut? I use Alt+r on some of my ReactJS webpages to re-render the whole site. This stopped working recently. Now when I press Alt+r, I see the little green "OK" on Reload Extensions' toolbar button.

**Comment by tylercollier** [comment]
The answer is yes, Alt+r is a keyboard shortcut. If I remove the extension, then my ability to intercept Alt+r works in my app.

**Comment by studgeek** [comment]
I created pull request #14 to add the info to the README.

It is probably worth noting that it defaults to Command-R on Mac, which means it both reloads the page and reloads extensions. It may be worth adding a different default for the Mac (like Opt-R).

**Comment by studgeek** [comment]
Note, I corrected my previous comment. The default is Opt-r on mac.

**Comment by Revadike** [comment]
Good idea!

**Comment by arikw** [comment]
Docs updated with the help of @studgeek. Thank you!
