### ISSUE TITLE
Improvement Request: Watch a folder

### ISSUE THREAD

**Issue by paganaye** [arikw/chrome-extensions-reloader#8]
Would be nice if you could look at at the extension folder and detect when a file has changed.

**Comment by amitg87** [comment]
Chrome extensions do not have access to file system and file events.
This is not happening.
Issue can be closed.

**Comment by mickdekkers** [comment]
@amitg87 while it is true that Chrome extensions do not have access to the file system, they are able to communicate with native applications that do. See https://developer.chrome.com/apps/nativeMessaging

Using Chrome's Native Messaging API, a Node.js (or any other language) app could be written to communicate with the Chrome extensions reloader, notifying it when the project files change. If it's a Node app, something like [Chokidar](https://github.com/paulmillr/chokidar) could be used to do the actual file watching.

**Comment by amitg87** [comment]
@mickdekkers - I agree, it can be done. 
But NodeJS app you are talking about is not a chrome extension. Once such NodeJS app is built - this extension can be integrated to it.
So until then this issue can parked/closed. New issue can be created about such integration in future.

**Comment by arikw** [comment]
Thank you all for your comments.
I would love to feature recipes of folder watching using 3rd party tools that trigger a reload using `http://reload.extensions` url, if someone would like to provide such examples
