### ISSUE TITLE
reload.extensions doesn't automatically close in Chrome 55

### ISSUE THREAD

**Issue by tdg5** [arikw/chrome-extensions-reloader#9]
Kind of seems like the extension is doing what it's supposed to be doing, but it doesn't seem to be working anymore. I tried to fix on my own but had no luck.

Seems kind of like two things are going on.

First, `redirectUrl` doesn't seem to respect `chrome-extension://` URLs anymore. I was able to make a data-url work as the redirect, and I was able to make a normal HTTP URL work as the redirect, but no love from chrome extension URLs.

The second thing I tried was to just self-host the close page and redirect to it. This kind of works in that at least the redirect is respected, but the tab doesn't close in this fashion. The console offers some clue as to why: "Scripts may close only the windows that were opened by it." 

Here's the HTML file I self hosted if you want to give it a try: http://static.tdg5.com.s3.amazonaws.com/close.html

I tried to look in the changelog for Chromium for reference to any of these changes, but didn't see anything, though I was mostly looking for references to onBeforeRequest.

I haven't dug into this much further and am not familiar with the extension, but if you have any other suggestions for getting the tab to auto-close, please let me know.

Thanks!

**Comment by tdg5** [comment]
If you end up looking at this, please reach out with any questions. As I've dug into this issue more, it seems likely that the reason that tab wasn't being closed was because it was the selected tab. Not sure why that would have changed or how that would be different, but it is something to consider when looking into this issue.

I made an aggressive tab closer branch here if it's of any interest to you or anyone else who wants more aggressive tab closing: https://github.com/tdg5/chrome-extensions-reloader/commit/da2eec0ede2158fc69b2e9a21151fa703c9fb9bc

**Comment by felixfbecker** [comment]
@tdg5 have you considered submitting a pull request for this?

**Comment by arikw** [comment]
Please reopen if issue still occurs
